name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf build-essential

    - name: Generate configure script (if needed)
      run: autoconf

    - name: Run configure
      run: ./configure

    - name: Build project
      run: make

    - name: Run tests (optional)
      run: make check
